# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: add6e3553488722de90e66e3621fa2fc0d8b8ae26ffd3de2cddf1baf6efbfc42af8879391ce78e2ecb88da37ddb9db6d37332a8363364ea394167994bc5a77d7

test:
  secret_key_base: 94611b75e7ca4b1227b4b20ada2ff029011deb6975fb489a5516e1af25051abff703e9dcec2dc9c8c16b9292ed029e6c65651c95fb3487e90c4d3bf7d0de3351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
